# You must change these to your own details.
[package]
name = "tari_wallet_lib"
version = "0.1.0"
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
tari_crypto = { version = "0.17" }

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.3.37"
